### PR TITLE
`rix::rix()` | `rix::rix_init()`: properly handle and close connections

### PR DESCRIPTION
**Pull request by philipp-baumann**
@b-rodrigues related to https://github.com/ropensci/rix/pull/306
i can also augment your PR

### CODE REVIEW

**Comment by b-rodrigues** [comment]
we would need to see if this handles detritus files and building of vignettes well

**Comment by philipp-baumann** [comment]
> we would need to see if this handles detritus files and building of vignettes well

yeah true; my hope was it would so. detrius is this env-... right?

**Comment by b-rodrigues** [comment]
and temporary folders that somehow don't get cleanup up when running tests and vignettes... even though we have on.exit(unlink(...)) everywhere

**Comment by philipp-baumann** [comment]
> and temporary folders that somehow don't get cleanup up when running tests and vignettes... even though we have on.exit(unlink(...)) everywhere

the tests in the nix devtools::test() runner do now pass with this PR:
https://github.com/ropensci/rix/actions/runs/10935184361/job/30356487077

**Comment by b-rodrigues** [comment]
tests were always OK, it's during check that these leftover files would be noted

**Comment by philipp-baumann** [comment]
launched rhub test at [5b30e5e](https://github.com/ropensci/rix/pull/308/commits/5b30e5eb89916df1578b9cac228f18956b81428c) : https://github.com/ropensci/rix/pull/308

**Pull request merged**
