### PR TITLE
helper functions to bootstrap from renv.lock 2

### PR DESCRIPTION
**Pull request by RichardJActon**
Resuming where we accidentally left off: https://github.com/ropensci/rix/pull/349

Partially addresses https://github.com/ropensci/rix/issues/5, this implements a "fast" inexact conversion from renv to nix environment description. It does **NOT** capture the exact package versions, just the R version and the list of packages in `renv.lock`, nor does it differentiate primary from transitive dependencies in `renv.lock` it simply lists all dependencies.

## To Do

- [ ] Finish testing on real world `renv.lock` examples, and handling any resulting edge cases
- [ ] Do any updates need to be made to the README / other docs about this?

### CODE REVIEW

**Comment by RichardJActon** [comment]
About excluding {renv} from `default.nix` (https://github.com/ropensci/rix/pull/349#issuecomment-2450366574), I'm not sure this is always a good idea.

I've been playing around with projects where both the {renv} and nix environment management are present and running an `renv::snapshot()` then using the resulting `renv.lock` to generate a `default.nix` via `renv2nix()` is quite handy to do on a local environment managed with nix.
This is especially the case when my remote system is still doing builds in CI based on the {renv} tooling and not nix yet, this lets me keep both up to date and approximately in sync.

I'd say if the {renv} package is in your `renv.lock` then it should end up in your `default.nix`. It's worth noting that {renv} does not necessarily end up in the lock file by default when you use {renv} to manage a project. I just happen to have picked a couple of examples where it is in there on purpose as I extract the version of {renv} I'm using in that project from the lock file to install the right version in the container my CI uses.

**Comment by b-rodrigues** [comment]
Thanks for reopening @RichardJActon and sorry again! Next time I want to add changes, I'll open a PR against your branch !

**Comment by b-rodrigues** [comment]
We can ignore the unit test not passing in CI, that's due to a known issue with Rcpp and R 4.4.2. A fix is coming to CRAN so this won't be an issue much longer

**Comment by b-rodrigues** [comment]
Looks like I was able to push without destroying the PR unlike last time :)
I’ll try to add some changes and merge by the end of the week

**Comment by b-rodrigues** [comment]
As discussed on matrix, we now merge this gather already some feedback before spending more time writing tests. Many thanks to @RichardJActon for this much requested feature!

**Pull request merged**
