### PR TITLE
Terminate `nix-build` background process for SIGINT interruption via ctrl+c

### PR DESCRIPTION
**Pull request by philipp-baumann**
addresses #304

### CODE REVIEW

**Comment by philipp-baumann** [comment]
Example. Use this `default.nix` that causes compilation.

```sh
# This file was generated by the {rix} R package v0.8.0 on 2024-09-18
# with following call:
# >rix::rix(r_ver = "9355fa86e6f27422963132c2c9aeedb0fb963d93",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = c("git",
#  > "quarto"),
#  > git_pkgs = git_pkgs,
#  > ide = "rstudio",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "export QT_XCB_GL_INTEGRATION=none")
# It uses nixpkgs' revision 9355fa86e6f27422963132c2c9aeedb0fb963d93 for reproducibility purposes
# which will install R as it was as of nixpkgs revision: 9355fa86e6f27422963132c2c9aeedb0fb963d93.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/9355fa86e6f27422963132c2c9aeedb0fb963d93.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      targets
      tarchetypes
      dplyr
      data_table
      dm
      DiagrammeR
      quarto
      R_utils
      here
      yaml
      readxl
      reactable
      writexl
      qs
      lgr
      devtools
      styler
      lintr;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "rix";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rix";
        rev = "c64ccaa34eb48ae4dcd78148ace211f72eebcb16";
        sha256 = "sha256-91L+sHO4eh9n1YqYMFcy9giG8VjefOooUhob8rAuwLs=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          codetools
          curl
          jsonlite
          sys;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "fnmate";
      src = pkgs.fetchgit {
        url = "https://github.com/MilesMcBain/fnmate/";
        rev = "18a4c00536e0deafeb6b3f91e48b53b641f47e6a";
        sha256 = "sha256-X/9WbeiDv7JEzVTEGA5LdMchUVsAtquO4YWiZjLXzhg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          magrittr
          purrr
          glue
          readr
          rstudioapi
          clipr
          rlang
          gert;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "rscodeio";
      src = pkgs.fetchgit {
        url = "https://github.com/anthonynorth/rscodeio";
        rev = "88a1a373d64f0bd81b6730eb6fa005fd0baa9078";
        sha256 = "sha256-6LBL4cjGwe2A0+JJr+6epxSuwAcEGtNqB6gm4DC4OP0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          fs
          purrr
          rstudioapi;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      quarto
      R
      glibcLocales
      nix;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages  wrapped_pkgs ];
  shellHook = "export QT_XCB_GL_INTEGRATION=none";
}
```

```r
devtools::load_all()
```

tested on linux and on macOS

```r
# This file was generated by the {rix} R package v0.8.0 on 2024-09-18
# with following call:
# >rix::rix(r_ver = "9355fa86e6f27422963132c2c9aeedb0fb963d93",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = c("git",
#  > "quarto"),
#  > git_pkgs = git_pkgs,
#  > ide = "rstudio",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "export QT_XCB_GL_INTEGRATION=none")
# It uses nixpkgs' revision 9355fa86e6f27422963132c2c9aeedb0fb963d93 for reproducibility purposes
# which will install R as it was as of nixpkgs revision: 9355fa86e6f27422963132c2c9aeedb0fb963d93.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/9355fa86e6f27422963132c2c9aeedb0fb963d93.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      targets
      tarchetypes
      dplyr
      data_table
      dm
      DiagrammeR
      quarto
      R_utils
      here
      yaml
      readxl
      reactable
      writexl
      qs
      lgr
      devtools
      styler
      lintr;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "rix";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rix";
        rev = "c64ccaa34eb48ae4dcd78148ace211f72eebcb16";
        sha256 = "sha256-91L+sHO4eh9n1YqYMFcy9giG8VjefOooUhob8rAuwLs=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          codetools
          curl
          jsonlite
          sys;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "fnmate";
      src = pkgs.fetchgit {
        url = "https://github.com/MilesMcBain/fnmate/";
        rev = "18a4c00536e0deafeb6b3f91e48b53b641f47e6a";
        sha256 = "sha256-X/9WbeiDv7JEzVTEGA5LdMchUVsAtquO4YWiZjLXzhg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          magrittr
          purrr
          glue
          readr
          rstudioapi
          clipr
          rlang
          gert;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "rscodeio";
      src = pkgs.fetchgit {
        url = "https://github.com/anthonynorth/rscodeio";
        rev = "88a1a373d64f0bd81b6730eb6fa005fd0baa9078";
        sha256 = "sha256-6LBL4cjGwe2A0+JJr+6epxSuwAcEGtNqB6gm4DC4OP0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          fs
          purrr
          rstudioapi;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      quarto
      R
      glibcLocales
      nix;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages  wrapped_pkgs ];
  shellHook = "export QT_XCB_GL_INTEGRATION=none";
}

``

**Comment by b-rodrigues** [comment]
Can we have a GitHub actions testing for this?

**Comment by philipp-baumann** [comment]
> Can we have a GitHub actions testing for this?

good question. I'll ask on ropensci slack

**Comment by philipp-baumann** [comment]
only {flint} pipeline is not working, apparently because of cache. Need more info to see whether automatic testing of SIGINT action (whether it cleans all background processes) properly, is suitable/feasable. Will open a separate issue.

**Review by b-rodrigues — COMMENTED** [review]
sorry I missed this but we have leftover skip_on_cran in test-fetchers that we need to remove

**Pull request merged**
